-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 21:01:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bloger
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bloger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bloger` DEFAULT CHARACTER SET utf8 ;
USE `bloger` ;

-- -----------------------------------------------------
-- Table `bloger`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloger`.`user_roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bloger`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloger`.`users` (
  `id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `users_role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `users_role_id_fk`
    FOREIGN KEY (`role_id`)
    REFERENCES `bloger`.`user_roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bloger`.`blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloger`.`blogs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `author_id` INT UNSIGNED NULL,
  `tittle` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `deleted_id` (`id` ASC) VISIBLE,
  INDEX `blogs_author_id_fk_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `blogs_author_id_fk`
    FOREIGN KEY (`author_id`)
    REFERENCES `bloger`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bloger`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloger`.`categories` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bloger`.`blogs_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloger`.`blogs_categories` (
  `id` INT UNSIGNED NOT NULL,
  `blogs_id` INT UNSIGNED NOT NULL,
  `categories_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `blogs_id` (`blogs_id` ASC) VISIBLE,
  INDEX `categories_id` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `blogs_categories_ibfk_1`
    FOREIGN KEY (`blogs_id`)
    REFERENCES `bloger`.`blogs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `blogs_categories_ibfk_2`
    FOREIGN KEY (`categories_id`)
    REFERENCES `bloger`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bloger`.`user_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloger`.`user_session` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NULL,
  `token` VARCHAR(60) NOT NULL,
  `user_agent` VARCHAR(500) NULL,
  `ip` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  INDEX `user_session_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_session_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `bloger`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
